### ISSUE TITLE
Django 1.8 compatability issues

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#206]
Got this error after pushing the latest updates. And after upgrading to Django 1.8, I got this `ProgrammingError: column django_content_type.name does not exist
LINE 1: ...rmission"."codename", "django_content_type"."id", "django_co...`  

I had to manually  `ALTER TABLE django_content_type ADD COLUMN name character varying(100) NOT NULL DEFAULT 'asdf';` 

I see this column is actually redundant so I am not sure whether this is a django issue. Did land into this when you upgraded?

**Comment by rowanseymour** [comment]
Did you do a clean install of your virtual env? I definitely saw this error a few times whilst playing with 1.8 but the final changes that went into master shouldn't be causing this.

**Comment by teehamaral** [comment]
After update and to run the migrate command, show error in Sentry when I try to create a new flow or I access flow change page : ProgrammingError: relation "flows_flowrevision" does not exist.
PS: Virtualenv already was updated with the new packages of the new version.

**Comment by rowanseymour** [comment]
@teehamaral that seems like a different issue. There's [a migration](https://github.com/nyaruka/rapidpro/blob/master/temba/flows/migrations/0039_auto_20151028_1648.py) to rename `FlowVersion` to `FlowRevision`. I'm assuming your db still has a table called `flows_flowversion`. Where there any errors when running the migrations?

**Comment by teehamaral** [comment]
@rowanseymour was solved. Thank you. To solve the problem, make a backup of the flows in the old version of RapidPro, removed the migrations of data from the table "django_migrations", we exclude the tables of flows in model and again execute the migrate command.

**Comment by xkmato** [comment]
So I ran into that as well(But I don't think it's related the issue above), the migrations were OK but updating flow revisions by the flow editor always returned 500.
This patch did it for me in `temba/flows/models.py -2304,7 +2304,8`;

                 revision = 1
    -            last_revision = self.revisions.order_by('-revision').first()
    +            if self.revisions.exists():
    +                last_revision = self.revisions.order_by('-revision')[0]
                 if last_revision:

This to me looks like the exact same thing but I guess django compiles them to different sql. 

And the error I was getting was ` ProgrammingError: relation "flows_flowversion" does not exist`, which I am guessing should not exist in the first place.

I am still trying to look into why this is, so I will update with more relevant info.

**Comment by rowanseymour** [comment]
@xkmato I think your problem is that that table didn't get renamed during [this migration](https://github.com/nyaruka/rapidpro/blob/master/temba/flows/migrations/0039_auto_20151028_1648.py). Can you try renaming it manually?

**Comment by xkmato** [comment]
:thumbsup: That works for me. Although I still don't know why the migration did work.
