### ISSUE TITLE
Ability to export a spreadsheet of all translated items in a flow

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#841]
This would allow users to more easily compare translations across different languages. Could even be an external tool.

From https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/all/conversations/20289912666

**Comment by rudigiesler** [comment]
At the moment we're solving this by doing a flow export, and then running the json through a script to extract the things we want to translate, and manually uploading the translated content. Would be great to be able to do this inside of RapidPro as a CSV import/export, or some other tool (our translators usually want a spreadsheet, so that limits services like pootle/transifix, but that's just for our use case)

**Comment by nicpottier** [comment]
Seems like PO files would be the most natural thing to use here, that's what it is built for.

There are really nice native tools to aid in translation like PoEdit:
  https://poedit.net/

Web based tools like Transifex and PoEditor that allow collaboration and if you do want to get into Excel, there are tools for that too:
  https://pypi.org/project/poxls/

This is an easy lift for us too as there's very little UI work, so can bang this out quickly.

**Comment by rowanseymour** [comment]
I guess on Excel vs PO files, it depends what the typical workflow is going to be. Excel files will work best if users want to export all translations in all languages, work on that, and then re-import. PO files will work best if they want to export a single language, send that to someone, re-import translations for that specific language.

An Excel file might help users see the level of translation across all languages. But we can also build something in the RapidPro UI to do that.

I think if we go the PO route then we'd want a UI (modal?) that lists each language, with its progress, with options for export/import.

If we went the whole hog and made a Transifex integration, then you could potentially sync all languages back and forth between that and RapidPro with a single click.. which could be very cool.

Either way I can start on having the engine extract localizable strings..

**Comment by rudigiesler** [comment]
For PO files, we could also do a download/upload zip file. We work with flows with 11 languages, so doing a separate download and upload for each would be painful, but still an improvement over the current system. 

The only challenge there is assigning each file to a language during upload. Could either be done using a UI, or by requiring the language code to be in the filename.

Usually the tools to work with PO files show you the level of translation across the languages, so I wouldn't worry too much about that if we're going the PO route (Excel route we might need it)

**Comment by ewheeler** [comment]
> If we went the whole hog and made a Transifex integration, then you could potentially sync all languages back and forth between that and RapidPro with a single click.. which could be very cool.

For whole hogs, check out Weblate too. Have seen a lot of FOSS projects move from Transifex to Weblate recently https://docs.weblate.org/en/latest/index.html

**Comment by nicpottier** [comment]
So just recording some thoughts we had on our weekly call.

1. It is probably useful to be able to export all translations across more than one flow. This is the use case of building a set of flows that you then want to pass off to some other person for import, a "program" if you will that you want to translate.
2. Alternatively it may be useful to treat this more as a org level export actually with shared strings across the flows. IE, then you only translate "Yes", "No" once per organization

Open questions / for consideration:
 * which one of 1 or 2 is most logical?
 * are these PO files backdowns for flow specific translations (IE, gettext-y string based translations) or when you import a po file do they go and overwrite the flow-specific translations that exist on flows? Adding another layer of backdowns for resolving translations may be a bit much, but at the same time unintended overwriting of translations may not be desirable. Is there a cleaner way of handling that we aren't thinking of? (I probably lean towards org level backdowns for translations FWIW, which also makes a vote for 2) above)

To me the idea of basically having translatable "strings" on an org which is populated by the set of flows you have on that org seems most logical. That addresses you creating a new flow easily "inheriting" translations you have previously done ("Yes", "No" other common cases) and it also makes it easy to piece-meal import PO files that contain useful translations for you to resolve to during flow execution.

Another related open question is perhaps whether the localization strategy we currently have for flows is correct. Right now we basically have a full dictionary of UUID->translatable text which we maintain per language, but perhaps this should really be something more like gettext where it is a simple list of string->string across languages. Our current approach is more granular but fails for the "Yes" is always translated the same case. Perhaps a step in that direction would be this idea of "env" level string-based PO files.

**Comment by rowanseymour** [comment]
Yeah I think the big question here is how our current approach maps to the gettext approach. PO files do have a concept of context, so we can choose how contextual we want to be...

 * no context, "Y" can be translated once

```po
msgid "Y"
msgstr "S"
```

 * context is the property name in the flow def:

```po
msgctxt "quick_replies"
msgid "Y"
msgstr "S"

msgctxt "text"
msgid "Y"
msgstr "And"
```

* context is the unique location.. what we do right now in flows:

```po
msgctxt "b8d1c24c-119f-4dcb-a993-cdcbc93cda05|quick_replies"
msgid "Y"
msgstr "S"

msgctxt "8a193efd-46b4-4a3f-838b-eb2996d8d575|quick_replies"
msgid "Y"
msgstr "Y"

msgctxt "b8d1c24c-119f-4dcb-a993-cdcbc93cda05|text"
msgid "Y"
msgstr "And"
```

I think I would agree that that if these are "backdowns" (i.e. you always have the option to override a translation in an exact location), then context is less important here. You could go with no context, and onus is on flow creators, to override specific points in flows where that isn't sufficient.

You could try to be smart when extracting text from flows. If you find _Yes_ being translated two different ways, then include that context in the PO, if you find _No_ is always _No_, list it without context. Maybe the translator could split it into two entries later if needed.

**Comment by nicpottier** [comment]
Hrmm, ya you bring up some good gotchas here. If we say translation is per-flow, then we introduce the problem of how to resolve "conflicts" in translation when trying to generate a PO file FROM flows. 

That "yes" means "yes" regardless of location definitely feels most right to me. And I think we have to humbly admit that the Unix gods who created gettext probably thought through this thoroughly enough that we are wrong if we insist otherwise. So I think string based keys with no context is probably the right answer.

One possible option would be to say that PO file generation only generates the possible translations without pulling in actual translations that have been done in a flow. In that world, flow editor translation and PO file translation are parallel worlds of sorts. The advantage there is you don't have to reason about conflicts in two flows having translated "Yes" differently in a single language.

That feels like a bit of a cop out though, it would be nice to be able to make updates to translations within RapidPro and have those take effect in the language specific PO files.

It almost feels to me that the place we have gone wrong here is to say that flows own translations as opposed to translations just being metadata that accompany a flow export etc.. IE, translations always live at the org level and when you export a flow we just happen to export metadata for relevant translations to that flow, which then get imported into the translations for the org upon import. Translations then ONLY live at the org level and ONLY as string based translations. Translation within the editor is really updating the org level translations, not the flow specific ones.

That is a really big change though.

I'm not sure I see a reasonable middle ground though.

Problem with the backdown strategy is that the process is then super confusing:
 1. User generates PO file, has translations pulled in from the flow translations they have already performed. Say they had a translation for "Yes" as "Si" already there, it is included in PO file.
 2. User modifies some of the translations in PO file then reimports, global translations updated accordingly. "Yes" is now translated to "Ya"
 3. During execution, old translation is still used "Si" because that is specific to the flow and we don't look at the new global backdown "Ya"

If you instead reverse the ordering (global first, then flow second) then it is similarly weird because what you see in the editor is not what happens during execution.

I think for this to work and make sense you really need to move to only having a single place where translations are stored: the environment.

**Comment by rowanseymour** [comment]
> I think we have to humbly admit that the Unix gods who created gettext probably thought through this thoroughly enough that we are wrong if we insist otherwise

I think the history of gettext shows the opposite of this is true. Developers came up with their own workarounds (see http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html) because it became apparent that context was sometimes essential and eventually GNU gettext adopted `msgctxt` as the standard. I think the anglocentric Unix gods cared much about internationalization as the people who invented ASCII.

It's not hard to think of lots of English words which mean different things in different contexts, "subject", "march", "may", "record", "run"... And it's not hard to think of ways in which other languages are a lot more context dependent than English (gender in romantic languages, noun classes in Bantu languages..)

I guess the thing that might let us get away with it is that text within flows isn't _typically_ single words, except things like quick replies. It's not like application menus which are lots of single words...

But I dunno.. seems a little short-sighted to say there would be no escape hatch here.

**Comment by nicpottier** [comment]
I mean the entire rest of RapidPro is done that way isn't it? Sure there are exceptions and I have no doubt they come up but we have gotten this far with our own product without having context haven't we?

I imagine the typical workaround it you subtly change the wording.

Remember that translators don't get a whole lot of context when doing translations, nor do they often have any understanding of the platform at all, so I'm not sure how much value is added in adding "quick replies" or a node UUID when looking a string in Transifex or the like.

**Comment by nicpottier** [comment]
So I guess to add to what you said, sure, context is important but we aren't really providing context with any kind of UUID or typing information. Feels to me that instead that would be something that would be additionally added to a node's translatable form to make it easier for translators in some way.

Or are you thinking of something different with regards to the context?

**Comment by rowanseymour** [comment]
> I mean the entire rest of RapidPro is done that way isn't it?

I don't think that can be the bar.. thus far we've never prioritized localization in the RapidPro UI. We're probably doing a terrible job but we get away with it because most _users_ speak some English. That's not an assumption that holds with _contacts_.

But I agree node UUIDs and property names doesn't really solve the problem either. I was more thinking that there needs to be an escape hatch to override org-level text at a specific location in a flow

But I think I prefer what you're suggesting re a way for users to provide their own context. It's appealing because it still allows the translations to be shared and all kept in one place. You could even borrow an idea from Gnome which apparently let's devs provide strings like: 

```po
#: utils/gatestyletreewidget.c:132
msgid "Text style|Normal"
msgstr "običan"
```

Where `Text style|` is just context and is always stripped a way. @norkans7 can correct my Kinyarwanda but then you have the option to do stuff like...

```po
msgid "People|many"
msgstr "benshi"

msgid "Things|many"
msgstr "nyinshi"
```

**Comment by rowanseymour** [comment]
Ok so unpacking this direction a bit more...

User saves a flow (base language = eng) with the localizable string "Hello"  That stores  "Hello" in their org-level string store. User can export a POT of the English strings, create new translations elsewhere, import those resultant PO files into RapidPro.

They can also translate directly from the editor and that saves new translations to the org-level string store.

Storing something like...

ID | Text
-|-
1 | Hello
2 | Goodbye

TextID | Lang | Text
-|-|-
1 | spa | Hola
1 | fra | Bonjour
2 | spa | Adios

Now when the flow is run, the engine has access to a "gettext" service, and can resolve Hello to Spanish and French, with the usual backdowns. Having this not be in the flow definition means that changes to the org-level string store affect running of the flow, without having to re-edit it. There's no more `localization` section in flows.

When we export this flow, the export file could have a strings section made up of all strings in the included flows...

```json
{
  "spa" : {
    "Hello": "Hola"
  },
  "fra" : {
    "Hello": "Bonjour"
  }
}
```

When importing that flow elsewhere.. might have to give the users some merge options like "Prefer theirs" and "Prefer mine".

There's probably a "Clean up" option which gets rid of any strings in the org-level store which aren't being used by active flows.

Where things get more complicated is orgs having flows with different base languages.. or orgs trying to change their default language. Maybe we have to say that an org has one flow authoring language at a time..

**Comment by nicpottier** [comment]
All that sounds right to me.

The last bit is indeed a wrench that I'm not sure how we get around. Almost feels to me like the PO files would be per "source" language and maybe then your first table has a "lang" field in it? Seems that's a requirement really.

Different authoring languages definitely feels like different PO files to me.

**Comment by norkans7** [comment]
Ahhhh nice try @rowanseymour  
```
msgid "People|many"
msgstr "benshi"

msgid "Things|many"
msgstr "byinshi"
```

**Comment by norkans7** [comment]
> pa

So this will be similar to the way we get the language to use from contact language, flow language and org language?

**Comment by norkans7** [comment]
> Ok so unpacking this direction a bit more...
> 
> User saves a flow (base language = eng) with the localizable string "Hello" That stores "Hello" in their org-level string store. User can export a POT of the English strings, create new translations elsewhere, import those resultant PO files into RapidPro.
> 
> They can also translate directly from the editor and that saves new translations to the org-level string store.
> 
> Storing something like...
> 
> ID	Text
> 1	Hello
> 2	Goodbye
> TextID	Lang	Text
> 1	spa	Hola
> 1	fra	Bonjour
> 2	spa	Adios
> Now when the flow is run, the engine has access to a "gettext" service, and can resolve Hello to Spanish and French, with the usual backdowns. Having this not be in the flow definition means that changes to the org-level string store affect running of the flow, without having to re-edit it. There's no more `localization` section in flows.
> 
> When we export this flow, the export file could have a strings section made up of all strings in the included flows...
> 
> ```json
> {
>   "spa" : {
>     "Hello": "Hola"
>   },
>   "fra" : {
>     "Hello": "Bonjour"
>   }
> }
> ```
> 
> When importing that flow elsewhere.. might have to give the users some merge options like "Prefer theirs" and "Prefer mine".
> 
> There's probably a "Clean up" option which gets rid of any strings in the org-level store which aren't being used by active flows.
> 
> Where things get more complicated is orgs having flows with different base languages.. or orgs trying to change their default language. Maybe we have to say that an org has one flow authoring language at a time..

So this will be similar to the way we get the language to use from contact language, flow language and org language?

**Comment by rowanseymour** [comment]
@norkans7 that's just the backdown order of languages we try to find translations in.. we're talking about moving the actual translations out of the flow definitions and storing them at an org-level. I think we'd still have the same backdowns.

@nicpottier yeah we need to stick language on the first table and then an org can have a mixture of translatable strings in different languages. When you ask for PO file you need to specify the source and target languages. Kinda awkward tho orgs probably don't switch base languages so often. More common is probably a UNICEF country office which usually authors in language X getting a flow in base language Y.

Trying to think of incremental ways we could get from here to there...

1. Editor still writes `localization` in flows but starts additionally saving translated text to a new endpoint that saves each text centrally.
2. Editor only sends translated items to the new endpoint, `localization` is generated on flow saves and added to the flow definition. At this point strings are being shared between flows.
3. Engine stops reading from `localization`, uses service instead.
4. Remove `localization` from flows.

**Comment by ericnewcomer** [comment]
One thing that sounds different here is that currently we represent some amount of structure in our flow-level localization (which is an escape hatch of sorts and likely an anti-pattenr). So for example, a user may add one quick reply in english, but two (or none) in spanish. Now, that isn't something we necessarily need to support, but it could potentially change behavior from how things work today and where we are hoping to end up with org-level localization. Another is rule-based translations. It feels this really wouldn't belong at the org-level so I'm not sure we'd want to remove flow-specific localization altogether.

Also, worth noting that changing this model is a pretty big lift on the editor side, for whatever that is worth. That said, I am quite fond of an org-gettext approach though.

**Comment by nicpottier** [comment]
> So for example, a user may add one quick reply in english, but two (or none) in spanish. 

Huh, that's a thing? Seems kinda crazy to imagine a scenario where that would be correct since for quick replies those almost always map to categories in the next split.

> Another is rule-based translations. 

That one is definitely more interesting and I think we still want to allow it, but again I would think the "structure" there is the same, IE, same number of rules, but perhaps different operands. Though in general I think we have found rarely is translating these the right thing. (very translated flows are generally better served using A,B,C or 1,2,3 rather than translating, red, blue, green)

**Comment by ericnewcomer** [comment]
To be clear, I'm not saying it's something that makes sense, it's just something that is possible today. Quick replies is represented as an arbitrary list in each language, not as a one-to-one translation of what's in the base language (which, agreed, would make a lot more sense, but here we are).

I'd much prefer a world where rules are not localized at all and all quick reply translations are one-to-one (and removing any other cases like this we are not thinking about at the moment). Maybe we start by surfacing those as an issue?

**Comment by rowanseymour** [comment]
I think what happens right now in the engine is we merge. If you have `["Red", "Green", "Blue"]` in the action, and `["Rojo", "Verde"]` in Spanish, then you get `["Rojo", "Verde", "Blue"]` running the flow in Spanish.

**Comment by rowanseymour** [comment]
> I'd much prefer a world where rules are not localized at all

Not sure I'm following here. Isn't it fairly common to have contains tests like "yeah yes yup" translated to "si sip" etc? Wouldn't it be simpler to treat those like any other translation?

**Comment by ericnewcomer** [comment]
That was in response to rules using A,B,C and 1,2,3, sorry shouldn't have conflated that.  Rules do feel different from the general messaging case just in how they behave and that they control routing. One worry I have along those lines is unintentional translation. Are there cases where you have some text that _can_ be localized, but you don't _want_ localized?

**Comment by rowanseymour** [comment]
For a lot of things.. we could probably say that most users probably don't want to translate them but there's almost certainly other users who do. Maybe a good example is the regex argument of the `has_pattern` test. There's almost certainly users using that in language specific ways.. but you can also imagine other users letting it get out of sync and causing themselves all sorts of confusion.

Or arguments to numerical tests.. or the group UUID in the `has_group` test.

Currently localization is just looking up an array of strings called `arguments` for all of these. Maybe we could be more particular and encode on the test arguments whether they are localizable or not, e.g. some way of specifying that `test` in `has_any_phrase(test, test)` is localizable but `group_uuid` in `has_group(list, group_uuid)` isn't.

**Comment by ericnewcomer** [comment]
Are you saying as a rule for all test types? Or having the definition also be able to delineate whether it wants a `has_any_phrase` to possibly be localized? I can't really seem to convince myself that it's safe to just localize things like `has_any_phrase` implicitly -- but I agree we likely need some way to explicitly do it.

**Comment by nicpottier** [comment]
Isn't the fact that we can have different length arrays for quick replies just an artifact (*cough* bug) of us not wanting to create unique UUIDs for each of those quick replies? Feels like all the places we use arrays of localization values kind of fall in that trap and are less than ideal really.

I think I fall on the side that rule operands (and split categories) should be able to be localized though usually won't. And for the operand case maybe we use `msgctxt` there to annotate that it belongs to a particular test type?

```
msgctxt "has_any_word:red blue green"
msgid "red blue green"
msgstr "rojo azul verde"
```

```

**Comment by rowanseymour** [comment]
> Isn't the fact that we can have different length arrays for quick replies just an artifact (cough bug)

I recall tweaking things on the engine side so that it did merging if it found different length arrays - that the editor was letting that happen was a bug but I think that's fixed now. I don't think there's anything inherently wrong with saying every translatable is an array. Even if you gave each quick_reply a UUID, you still have the possibility that a translation doesn't have values for all the quick_replies in the base language... and the solution will still be to use backdowns to return the same number of quick_replies.

**Comment by rowanseymour** [comment]
Have been testing extracting localizable strings from flows today.. and looking at all those translated paragraphs with embedded expressions.. it does make you start to wonder how much users are going to like the idea that translations have to match exactly... i.e. assuming we really embrace the gettext philosophy, if they tweak some punctuation in the base translation.. they've just lost whatever translations of that text had been previously made.

It's the sort of thing we might be able to improve with tooling that shows very similar translatable strings.. or fuzzy matching.. but it's definitely going to be a big change for users that they may or may not like.

**Comment by nicpottier** [comment]
Good point that we don't want minor changes to be too destructive. Since we are managing our own PO file generation and translations it does seem we have a lot of clues to make that better though. IE, we know what node DO map to a translation and if the edit distance there is close enough we could pair them up automatically to the already translated strings.

**Comment by ericnewcomer** [comment]
Editor currently allows unique sets of quick replies per language, so that "bug" still exists.

**Comment by cbunicef** [comment]
Two additional things to consider, this may not affect the work at all.
1. Sometimes we include @() expressions in Send Message boxes. Some elements of those expressions will be translated and some not
2. Sometimes we want to translate "Save as Flow Results" rulesets. Currently we accomplish this by Split by Expression on Language, then using Save as Flow Results separately for each language

**Comment by rowanseymour** [comment]
@cbunicef interesting, can you give me an example of something you would want to save via _Save as Flow Results_ that's language specific? I'm wondering if we can find a better way to accomplish that.

**Comment by cbunicef** [comment]
No doubt this is off-label/hacky but here are a few places:

We are setting an error message to be used throughout the flow, adjusted by language. We use the _Save as Flow Results_ so that we don't have to repeat it over and over throughout the flow, and later in the flow we adjust the message based on the channel the user is on. This is not required but makes things simpler:
![image](https://user-images.githubusercontent.com/30042226/77925453-2ab69300-72a5-11ea-83d2-17dd6880c89d.png)

Here we are letting a user navigate between menu options without going back to the main menu. We cheat and "pretending" they selected the new menu option at the main menu by manually setting the value for variable we use in the _Wait for Response_:
![image](https://user-images.githubusercontent.com/30042226/77934841-f21cb680-72b0-11ea-8f76-1e0ff5880266.png)

These are both from U-Report Global workspace and this flow: https://app.rapidpro.io/flow/editor_next/5c221e77-7c97-45f0-84f9-82aeb3b91a29/

I'm assuming this isn't very clear, but as I said these are hacky solutions.

**Comment by rowanseymour** [comment]
Well any time users resort to doing something hacky we have to ask ourselves if we're missing something in the product. It would be nice if we could avoid users building localization systems within already localized flows.. it does make me wonder if this couldn't be something like Whatsapp templates but accessible across all channel types.

**Comment by rudigiesler** [comment]
There are already global variables, are those translatable? Maybe that can be used.

For the second use case, I'm sure that could be solve by rather splitting on the `category` of the wait for response, rather than the value.

**Comment by nicpottier** [comment]
Ya, this definitely feels more like a template of sorts.

**Comment by cbunicef** [comment]
Request: Please allow for "translation" of eg English text over existing English language. This will allow us to maintain multiple versions of text for a single flow, eg for audiences of different literacy levels.

**Comment by rowanseymour** [comment]
The best way to model that would be as a distinct language... but unfortunately there's no ISO standard for something like "simplified English" (e.g. wikipedia just puts it on a domain called simple https://simple.wikipedia.org/wiki/Main_Page)

**Comment by nicpottier** [comment]
@cbunicef you could always just use another language to represent that, ie, "Old English" for your simplified version etc..

**Comment by cbunicef** [comment]
Thanks for all the work on this so far, the PO feature is already useful for moving translations between flows and workspaces.

Duplicating my support email here: It would be helpful to have more context when doing translation. I have noticed two areas of importance:

1. What were the flow elements before this string that influence its content? Eg the Message sent before a Wait for Response the translator is working on. 

This can:
impact how words are gendered or conjugated
clarify Messages that are based on other messages ("Do you use RapidPro?" Yes **"How?"**)
give important translation context when short category names can have multiple meanings

2. Whether an item to be translated is a Message, Category, matching string

This can help translators understand why an element is not a grammatical sentence (matching string), or is shortened/abbreviated (Category).

When we share content with translators, today we do it in Excel. We generally populate the Excel sheet by following the natural user progression through the flow as we copy/paste, eg

"Do you use RapidPro? YES or NO"
"YES"
"NO"
"Sorry we didn't understand."
"How?"

Even without additional information marking YES/NO as Category Names, it's more or less clear. Maybe there is a way to order the flow elements like this during the export process? Not sure how it would be possible, but maybe the RapidPro user could select the elements to be included in order from the visual flow editor..

**Comment by rowanseymour** [comment]
Been pondering on this and I am left wondering if the gettext/PO approach is really the right fit for how you guys do translation. But there's some room for tweaking here...

Generally the PO approach is about making translations as universal and re-usable as possible. "Other" should only need to be translated once regardless of where it occurs. In fact our initial thought on PO support was that it would be across a batch of flows... or even an org-level thing.

Obviously where that runs into difficulties is where translations differ based on context, and most languages are more context dependent than English, e.g. "Other" in Spanish is going to be "Otro" or "Otra" depending on whether it refers to persons or places etc.

PO file entries have to be unique so you can't just include "Other" twice - we need to give them context to be make them unique. We currently do this where we find translation mismatches - e.g. maybe someone has already translated the flow into Spanish and Other has been translated as both Otra and Otro. In that case we'll have two entries in the PO file and we'll use the action UUID from the flow to make the entries unique, e.g.

```po
#: Translated/d1ce3c92-7025-4607-a910-444361a6b9b3/name:0
msgctxt "d1ce3c92-7025-4607-a910-444361a6b9b3/name:0"
msgid "Red"
msgstr "Roja"

#: Translated/e42deebf-90fa-4636-81cb-d247a3d3ba75/quick_replies:0
msgctxt "e42deebf-90fa-4636-81cb-d247a3d3ba75/quick_replies:0"
msgid "Red"
msgstr "Rojo"
```

Which in POEdit looks like...

<img width="623" alt="Captura de Pantalla 2020-04-20 a la(s) 14 46 46" src="https://user-images.githubusercontent.com/675558/79793214-ce7be780-8315-11ea-8b61-c7cd9719ebcc.png">

It's not intended to help the translator - it's to tell RapidPro where to put this translation when you're importing the PO file back into RapidPro.

It sounds like it would be more useful to you to have a PO file where every bit of translatable text in a flow 1) gets its own entry with context 2) is kept in order... 

Order could be a tricky one - currently we can extract text in the Y order that it appears in the flow.. but Y order is not necessarily the same as flow order.. contacts can move sideways through flows.. take different branches.

Another thing we could do is try to provide some more user-friendly context via comments, e.g. if we include stuff like in the entry comments..

```po
# send_msg: What's your favorite color?
# quick_replies: 0
#: Translated/e42deebf-90fa-4636-81cb-d247a3d3ba75/quick_replies:0
msgctxt "e42deebf-90fa-4636-81cb-d247a3d3ba75/quick_replies:0"
msgid "Red"
msgstr "Rojo"
```

Then POEdit shows that to the translator like..

<img width="754" alt="Captura de Pantalla 2020-04-20 a la(s) 15 03 49" src="https://user-images.githubusercontent.com/675558/79794748-6e3a7500-8318-11ea-8cc4-63e1f5ed2b32.png">

Where that gets tricky is where useful contextual information is on the preceding node rather than the  same action

**Comment by nicpottier** [comment]
I have some worry about diving too deep on this edge case.

IE, Chris you can take the generated source PO file and annotate it with comments that are far more useful than we will be able to generate before passing it on to your translators. For the case where translators don't have a lot of other context I think that is a pretty typical workflow. This basically mimics what you were doing with Excel except you can now import those translations back into RapidPro much more easily.

From a cost/benefit perspective I think the current functionality gives us all the flexibility needed. Things can always be made better but I think it is time for us to focus on other pieces of work that could have higher impact unless the solution of annotating yourself is somehow untenable.
